name: Check For PRs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * 3,6"
  check_suite:
    types:
      - completed
  pull_request_review:
    types:
      - submitted
jobs:
  automerge:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: Auto merge PRs
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          MERGE_LABELS: "dependencies"
          MERGE_RETRY_SLEEP: "60000"
          MERGE_FILTER_AUTHOR: "dependabot[bot]"
      - id: lock
        name: Lock merged PRs
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          gh pr lock ${{ steps.automerge.outputs.pullRequestNumber }} --reason "dependabot update done"
        env:
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
